/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface NewOrder {
  'contactInfo' : string,
  'shippingAddress' : string,
  'items' : Array<OrderItem>,
}
export interface Order {
  'id' : OrderId,
  'total' : bigint,
  'customer' : Principal,
  'createdAt' : Time,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem { 'productId' : ProductId, 'quantity' : Quantity }
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'image' : string,
  'price' : bigint,
}
export type ProductId = bigint;
export type Quantity = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<[string, bigint, string, string], ProductId>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[NewOrder], OrderId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setProductAvailability' : ActorMethod<[ProductId, boolean], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];